# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-24 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20170724_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropzonemodel',
            name='user',
        ),
    ]
