# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-25 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0003_remove_dropzonemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropzonemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
